#!/bin/bash

EKU_GCC_FLAGS='-D EKLAVYA -g -Wall -Wpedantic -Wno-sign-compare'
EKU_GPP_FLAGS="$EKU_GCC_FLAGS"

alias  g++03='g++ -std=c++03'
alias  g++11='g++ -std=c++11'
alias  g++14='g++ -std=c++14'
alias  g++17='g++ -std=c++1z'
alias   eg++="g++ -std=c++11 $EKU_GPP_FLAGS"
alias eg++03="g++ -std=c++03 $EKU_GPP_FLAGS"
alias eg++11="g++ -std=c++11 $EKU_GPP_FLAGS"
alias eg++14="g++ -std=c++14 $EKU_GPP_FLAGS"
alias eg++17="g++ -std=c++1z $EKU_GPP_FLAGS"

alias  gcc90='gcc -std=c90'
alias  gcc99='gcc -std=c99'
alias  gcc11='gcc -std=c11'
alias   egcc="gcc $EKU_GCC_FLAGS"
alias egcc90="gcc -std=c90 $EKU_GCC_FLAGS"
alias egcc99="gcc -std=c99 $EKU_GCC_FLAGS"
alias egcc11="gcc -std=c11 $EKU_GCC_FLAGS"

