#!/bin/bash

# This script is used to set a good prompt.
# To change your prompt, just run:
#
# PROMPT_COMMAND=prompt_setting_function
#
# You can also use one of the 4 ready-made functions made by me:
#
# PROMPT_COMMAND=prompt_command_small_bold
#
# You can also use the color codes written by me to make
# your own colored prompt-setting-function

# This script uses https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
if [ -f ~/ext_bin/git-prompt.sh ]; then
    source ~/ext_bin/git-prompt.sh
fi

GIT_PS1_SHOWDIRTYSTATE=''
GIT_PS1_SHOWUNTRACKEDFILES=''
GIT_PS1_SHOWCOLORHINTS=''

export RCol='\[\e[0m\]'
export Red='\[\e[0;31m\]'
export Gre='\[\e[0;32m\]'
export Blu='\[\e[0;34m\]'
export BRed='\[\e[1;31m\]'
export BGre='\[\e[1;32m\]'
export BBlu='\[\e[1;34m\]'

export prompt_small="${Gre}\u@\h${RCol}:${Blu}\W${RCol}"
export prompt_big="${Gre}\u@\h${RCol}:${Blu}\w${RCol}"
export prompt_small_bold="${BGre}\u@\h${RCol}:${BBlu}\W${RCol}"
export prompt_big_bold="${BGre}\u@\h${RCol}:${BBlu}\w${RCol}"

function prompt_command()
{
    local EXIT="$?"
    PS1=""

    # add virtualenv name
    if [ -n "$VIRTUAL_ENV" ]; then
        local venv_name=$(basename "$VIRTUAL_ENV")
        PS1+="($venv_name)"
    fi
    if [ -n "$CONDA_PREFIX" ]; then
        local conda_name=$(basename "$CONDA_PREFIX")
        PS1+="($conda_name)"
    fi

    # add a '*' if dotfiles have changed
    if [ -n "$TRACK_DOTFILES" ] && [ -d "$DOTFILES_DIR" ]; then
        pushd "$DOTFILES_DIR" > /dev/null
        if ! git diff --quiet --ignore-submodules HEAD ; then
            PS1+='*'
        fi
        popd > /dev/null
    fi

    # add exit status
    if [ "$EXIT" != 0 ]; then
        PS1+="${Red}($EXIT)${RCol}"
    else
        PS1+="${Gre}($EXIT)${RCol}"
    fi

    # add main prompt stuff
    PS1+="$1"

    # add git prompt
    if [ -d ".git" ]; then
        if command -v __git_ps1 > /dev/null ; then
            PS1+="\$(__git_ps1)"
        fi
    fi

    # add '$' for user and '#' for superuser
    if [ "$UID" == "0" ]; then
        PS1+='# '
    else
        PS1+='$ '
    fi
}

export -f prompt_command

function prompt_command_small()
{ prompt_command "$prompt_small"; }
function prompt_command_big()
{ prompt_command "$prompt_big"; }
function prompt_command_small_bold()
{ prompt_command "$prompt_small_bold"; }
function prompt_command_big_bold()
{ prompt_command "$prompt_big_bold"; }

export -f prompt_command_small
export -f prompt_command_big
export -f prompt_command_small_bold
export -f prompt_command_big_bold

PROMPT_COMMAND=prompt_command_small
