#!/bin/bash

_MAVEN_HOME="/opt/apache-maven"
if [ -d "$_MAVEN_HOME" ] ; then
    PATH="$PATH:$_MAVEN_HOME/bin"
    MAVEN_HOME="$_MAVEN_HOME"
fi

_ANT_HOME="/opt/apache-ant"
if [ -d "$_ANT_HOME" ] ; then
    PATH="$PATH:$_ANT_HOME/bin"
    ANT_HOME="$_ANT_HOME"
fi
